export const prefData = [
  {
    id: 1,
    name: "北海道",
    nameKana: "ほっかいどう",
    city: "札幌市",
    cityKana: "さっぽろし",
    imgSingle: "img/imgSingle/hokkaidoSingle.png",
    imgRegion: "img/imgRegion/hokkaidoRegion.png",
    imgCountry: "img/imgCountry/hokkaidoCountry.png",
  },
  {
    id: 2,
    name: "青森県",
    nameKana: "あおもりけん",
    city: "青森市",
    cityKana: "あおもりし",
    imgSingle: "img/imgSingle/aomoriSingle.png",
    imgRegion: "img/imgRegion/aomoriRegion.png",
    imgCountry: "img/imgCountry/aomoriCountry.png",
  },
  {
    id: 3,
    name: "岩手県",
    nameKana: "いわてけん",
    city: "盛岡市",
    cityKana: "もりおかし",
    imgSingle: "img/imgSingle/iwateSingle.png",
    imgRegion: "img/imgRegion/iwateRegion.png",
    imgCountry: "img/imgCountry/iwateCountry.png",
  },
  {
    id: 4,
    name: "宮城県",
    nameKana: "みやぎけん",
    city: "仙台市",
    cityKana: "せんだいし",
    imgSingle: "img/imgSingle/miyagiSingle.png",
    imgRegion: "img/imgRegion/miyagiRegion.png",
    imgCountry: "img/imgCountry/miyagiCountry.png",
  },
  {
    id: 5,
    name: "秋田県",
    nameKana: "あきたけん",
    city: "秋田市",
    cityKana: "あきたし",
    imgSingle: "img/imgSingle/akitaSingle.png",
    imgRegion: "img/imgRegion/akitaRegion.png",
    imgCountry: "img/imgCountry/akitaCountry.png",
  },
  {
    id: 6,
    name: "山形県",
    nameKana: "やまがたけん",
    city: "山形市",
    cityKana: "やまがたし",
    imgSingle: "img/imgSingle/yamagataSingle.png",
    imgRegion: "img/imgRegion/yamagataRegion.png",
    imgCountry: "img/imgCountry/yamagataCountry.png",
  },
  {
    id: 7,
    name: "福島県",
    nameKana: "ふくしまけん",
    city: "福島市",
    cityKana: "ふくしまし",
    imgSingle: "img/imgSingle/fukushimaSingle.png",
    imgRegion: "img/imgRegion/fukushimaRegion.png",
    imgCountry: "img/imgCountry/fukushimaCountry.png",
  },
  {
    id: 8,
    name: "茨城県",
    nameKana: "いばらきけん",
    city: "水戸市",
    cityKana: "みとし",
    imgSingle: "img/imgSingle/ibarakiSingle.png",
    imgRegion: "img/imgRegion/ibarakiRegion.png",
    imgCountry: "img/imgCountry/ibarakiCountry.png",
  },
  {
    id: 9,
    name: "栃木県",
    nameKana: "とちぎけん",
    city: "宇都宮市",
    cityKana: "うつのみやし",
    imgSingle: "img/imgSingle/tochigiSingle.png",
    imgRegion: "img/imgRegion/tochigiRegion.png",
    imgCountry: "img/imgCountry/tochigiCountry.png",
  },
  {
    id: 10,
    name: "群馬県",
    nameKana: "ぐんまけん",
    city: "前橋市",
    cityKana: "まえばしし",
    imgSingle: "img/imgSingle/gunmaSingle.png",
    imgRegion: "img/imgRegion/gunmaRegion.png",
    imgCountry: "img/imgCountry/gunmaCountry.png",
  },
  {
    id: 11,
    name: "埼玉県",
    nameKana: "さいたまけん",
    city: "さいたま市",
    cityKana: "さいたまし",
    imgSingle: "img/imgSingle/saitamaSingle.png",
    imgRegion: "img/imgRegion/saitamaRegion.png",
    imgCountry: "img/imgCountry/saitamaCountry.png",
  },
  {
    id: 12,
    name: "千葉県",
    nameKana: "ちばけん",
    city: "千葉市",
    cityKana: "ちばし",
    imgSingle: "img/imgSingle/chibaSingle.png",
    imgRegion: "img/imgRegion/chibaRegion.png",
    imgCountry: "img/imgCountry/chibaCountry.png",
  },
  {
    id: 13,
    name: "東京都",
    nameKana: "とうきょうと",
    city: "東京23区",
    cityKana: "とうきょう23く",
    imgSingle: "img/imgSingle/tokyoSingle.png",
    imgRegion: "img/imgRegion/tokyoRegion.png",
    imgCountry: "img/imgCountry/tokyoCountry.png",
  },
  {
    id: 14,
    name: "神奈川県",
    nameKana: "かながわけん",
    city: "横浜市",
    cityKana: "よこはまし",
    imgSingle: "img/imgSingle/kanagawaSingle.png",
    imgRegion: "img/imgRegion/kanagawaRegion.png",
    imgCountry: "img/imgCountry/kanagawaCountry.png",
  },
  {
    id: 15,
    name: "新潟県",
    nameKana: "にいがたけん",
    city: "新潟市",
    cityKana: "にいがたし",
    imgSingle: "img/imgSingle/nigataSingle.png",
    imgRegion: "img/imgRegion/nigataRegion.png",
    imgCountry: "img/imgCountry/nigataCountry.png",
  },
  {
    id: 16,
    name: "富山県",
    nameKana: "とやまけん",
    city: "富山市",
    cityKana: "とやまし",
    imgSingle: "img/imgSingle/toyamaSingle.png",
    imgRegion: "img/imgRegion/toyamaRegion.png",
    imgCountry: "img/imgCountry/toyamaCountry.png",
  },
  {
    id: 17,
    name: "石川県",
    nameKana: "いしかわけん",
    city: "金沢市",
    cityKana: "かなざわし",
    imgSingle: "img/imgSingle/ishikawaSingle.png",
    imgRegion: "img/imgRegion/ishikawaRegion.png",
    imgCountry: "img/imgCountry/ishikawaCountry.png",
  },
  {
    id: 18,
    name: "福井県",
    nameKana: "ふくいけん",
    city: "福井市",
    cityKana: "ふくいし",
    imgSingle: "img/imgSingle/fukuiSingle.png",
    imgRegion: "img/imgRegion/fukuiRegion.png",
    imgCountry: "img/imgCountry/fukuiCountry.png",
  },
  {
    id: 19,
    name: "山梨県",
    nameKana: "やまなしけん",
    city: "甲府市",
    cityKana: "こうふし",
    imgSingle: "img/imgSingle/yamanashiSingle.png",
    imgRegion: "img/imgRegion/yamanashiRegion.png",
    imgCountry: "img/imgCountry/yamanashiCountry.png",
  },
  {
    id: 20,
    name: "長野県",
    nameKana: "ながのけん",
    city: "長野市",
    cityKana: "ながのし",
    imgSingle: "img/imgSingle/naganoSingle.png",
    imgRegion: "img/imgRegion/naganoRegion.png",
    imgCountry: "img/imgCountry/naganoCountry.png",
  },
  {
    id: 21,
    name: "岐阜県",
    nameKana: "ぎふけん",
    city: "岐阜市",
    cityKana: "ぎふし",
    imgSingle: "img/imgSingle/gifuSingle.png",
    imgRegion: "img/imgRegion/gifuRegion.png",
    imgCountry: "img/imgCountry/gifuCountry.png",
  },
  {
    id: 22,
    name: "静岡県",
    nameKana: "しずおかけん",
    city: "静岡市",
    cityKana: "しずおかし",
    imgSingle: "img/imgSingle/shizuokaSingle.png",
    imgRegion: "img/imgRegion/shizuokaRegion.png",
    imgCountry: "img/imgCountry/shizuokaCountry.png",
  },
  {
    id: 23,
    name: "愛知県",
    nameKana: "あいちけん",
    city: "名古屋市",
    cityKana: "なごやし",
    imgSingle: "img/imgSingle/aichiSingle.png",
    imgRegion: "img/imgRegion/aichiRegion.png",
    imgCountry: "img/imgCountry/aichiCountry.png",
  },
  {
    id: 24,
    name: "三重県",
    nameKana: "みえけん",
    city: "津市",
    cityKana: "つし",
    imgSingle: "img/imgSingle/mieSingle.png",
    imgRegion: "img/imgRegion/mieRegion.png",
    imgCountry: "img/imgCountry/mieCountry.png",
  },
  {
    id: 25,
    name: "滋賀県",
    nameKana: "しがけん",
    city: "大津市",
    cityKana: "おおつし",
    imgSingle: "img/imgSingle/shigaSingle.png",
    imgRegion: "img/imgRegion/shigaRegion.png",
    imgCountry: "img/imgCountry/shigaCountry.png",
  },
  {
    id: 26,
    name: "京都府",
    nameKana: "きょうとふ",
    city: "京都市",
    cityKana: "きょうとし",
    imgSingle: "img/imgSingle/kyotoSingle.png",
    imgRegion: "img/imgRegion/kyotoRegion.png",
    imgCountry: "img/imgCountry/kyotoCountry.png",
  },
  {
    id: 27,
    name: "大阪府",
    nameKana: "おおさかふ",
    city: "大阪市",
    cityKana: "おおさかし",
    imgSingle: "img/imgSingle/osakaSingle.png",
    imgRegion: "img/imgRegion/osakaRegion.png",
    imgCountry: "img/imgCountry/osakaCountry.png",
  },
  {
    id: 28,
    name: "兵庫県",
    nameKana: "ひょうごけん",
    city: "神戸市",
    cityKana: "こうべし",
    imgSingle: "img/imgSingle/hyogoSingle.png",
    imgRegion: "img/imgRegion/hyogoRegion.png",
    imgCountry: "img/imgCountry/hyogoCountry.png",
  },
  {
    id: 29,
    name: "奈良県",
    nameKana: "ならけん",
    city: "奈良市",
    cityKana: "ならし",
    imgSingle: "img/imgSingle/naraSingle.png",
    imgRegion: "img/imgRegion/naraRegion.png",
    imgCountry: "img/imgCountry/naraCountry.png",
  },
  {
    id: 30,
    name: "和歌山県",
    nameKana: "わかやまけん",
    city: "和歌山市",
    cityKana: "わかやまし",
    imgSingle: "img/imgSingle/wakayamaSingle.png",
    imgRegion: "img/imgRegion/wakayamaRegion.png",
    imgCountry: "img/imgCountry/wakayamaCountry.png",
  },
  {
    id: 31,
    name: "鳥取県",
    nameKana: "とっとりけん",
    city: "鳥取市",
    cityKana: "とっとりし",
    imgSingle: "img/imgSingle/tottoriSingle.png",
    imgRegion: "img/imgRegion/tottoriRegion.png",
    imgCountry: "img/imgCountry/tottoriCountry.png",
  },
  {
    id: 32,
    name: "島根県",
    nameKana: "しまねけん",
    city: "松江市",
    cityKana: "まつえし",
    imgSingle: "img/imgSingle/shimaneSingle.png",
    imgRegion: "img/imgRegion/shimaneRegion.png",
    imgCountry: "img/imgCountry/shimaneCountry.png",
  },
  {
    id: 33,
    name: "岡山県",
    nameKana: "おかやまけん",
    city: "岡山市",
    cityKana: "おかやまし",
    imgSingle: "img/imgSingle/okayamaSingle.png",
    imgRegion: "img/imgRegion/okayamaRegion.png",
    imgCountry: "img/imgCountry/okayamaCountry.png",
  },
  {
    id: 34,
    name: "広島県",
    nameKana: "ひろしまけん",
    city: "広島市",
    cityKana: "ひろしまし",
    imgSingle: "img/imgSingle/hiroshimaSingle.png",
    imgRegion: "img/imgRegion/hiroshimaRegion.png",
    imgCountry: "img/imgCountry/hiroshimaCountry.png",
  },
  {
    id: 35,
    name: "山口県",
    nameKana: "やまぐちけん",
    city: "山口市",
    cityKana: "やまぐちし",
    imgSingle: "img/imgSingle/yamaguchiSingle.png",
    imgRegion: "img/imgRegion/yamaguchiRegion.png",
    imgCountry: "img/imgCountry/yamaguchiCountry.png",
  },
  {
    id: 36,
    name: "徳島県",
    nameKana: "とくしまけん",
    city: "徳島市",
    cityKana: "とくしまし",
    imgSingle: "img/imgSingle/tokushimaSingle.png",
    imgRegion: "img/imgRegion/tokushimaRegion.png",
    imgCountry: "img/imgCountry/tokushimaCountry.png",
  },
  {
    id: 37,
    name: "香川県",
    nameKana: "かがわけん",
    city: "高松市",
    cityKana: "たかまつし",
    imgSingle: "img/imgSingle/kagawaSingle.png",
    imgRegion: "img/imgRegion/kagawaRegion.png",
    imgCountry: "img/imgCountry/kagawaCountry.png",
  },
  {
    id: 38,
    name: "愛媛県",
    nameKana: "えひめけん",
    city: "松山市",
    cityKana: "まつやまし",
    imgSingle: "img/imgSingle/ehimeSingle.png",
    imgRegion: "img/imgRegion/ehimeRegion.png",
    imgCountry: "img/imgCountry/ehimeCountry.png",
  },
  {
    id: 39,
    name: "高知県",
    nameKana: "こうちけん",
    city: "高知市",
    cityKana: "こうちし",
    imgSingle: "img/imgSingle/kochiSingle.png",
    imgRegion: "img/imgRegion/kochiRegion.png",
    imgCountry: "img/imgCountry/kochiCountry.png",
  },
  {
    id: 40,
    name: "福岡県",
    nameKana: "ふくおかけん",
    city: "福岡市",
    cityKana: "ふくおかし",
    imgSingle: "img/imgSingle/fukuokaSingle.png",
    imgRegion: "img/imgRegion/fukuokaRegion.png",
    imgCountry: "img/imgCountry/fukuokaCountry.png",
  },
  {
    id: 41,
    name: "佐賀県",
    nameKana: "さがけん",
    city: "佐賀市",
    cityKana: "さがし",
    imgSingle: "img/imgSingle/sagaSingle.png",
    imgRegion: "img/imgRegion/sagaRegion.png",
    imgCountry: "img/imgCountry/sagaCountry.png",
  },
  {
    id: 42,
    name: "長崎県",
    nameKana: "ながさきけん",
    city: "長崎市",
    cityKana: "ながさきし",
    imgSingle: "img/imgSingle/nagasakiSingle.png",
    imgRegion: "img/imgRegion/nagasakiRegion.png",
    imgCountry: "img/imgCountry/nagasakiCountry.png",
  },
  {
    id: 43,
    name: "熊本県",
    nameKana: "くまもとけん",
    city: "熊本市",
    cityKana: "くまもとし",
    imgSingle: "img/imgSingle/kumamotoSingle.png",
    imgRegion: "img/imgRegion/kumamotoRegion.png",
    imgCountry: "img/imgCountry/kumamotoCountry.png",
  },
  {
    id: 44,
    name: "大分県",
    nameKana: "おおいたけん",
    city: "大分市",
    cityKana: "おおいたし",
    imgSingle: "img/imgSingle/oitaSingle.png",
    imgRegion: "img/imgRegion/oitaRegion.png",
    imgCountry: "img/imgCountry/oitaCountry.png",
  },
  {
    id: 45,
    name: "宮崎県",
    nameKana: "みやざきけん",
    city: "宮崎市",
    cityKana: "みやざきし",
    imgSingle: "img/imgSingle/miyazakiSingle.png",
    imgRegion: "img/imgRegion/miyazakiRegion.png",
    imgCountry: "img/imgCountry/miyazakiCountry.png",
  },
  {
    id: 46,
    name: "鹿児島県",
    nameKana: "かごしまけん",
    city: "鹿児島市",
    cityKana: "かごしまし",
    imgSingle: "img/imgSingle/kagoshimaSingle.png",
    imgRegion: "img/imgRegion/kagoshimaRegion.png",
    imgCountry: "img/imgCountry/kagoshimaCountry.png",
  },
  {
    id: 47,
    name: "沖縄県",
    nameKana: "おきなわけん",
    city: "那覇市",
    cityKana: "なはし",
    imgSingle: "img/imgSingle/okinawaSingle.png",
    imgRegion: "img/imgRegion/okinawaRegion.png",
    imgCountry: "img/imgCountry/okinawaCountry.png",
  },
];
