export const pref2 = [
  {
    id: 1,
    name: "北海道",
    nameRoman: hokkaido,
    nameKana: "ほっかいどう",
    city: "札幌市",
    cityKana: "さっぽろし",
  },
  {
    id: 2,
    name: "青森県",
    nameRoman: "aomori",
    nameKana: "あおもりけん",
    city: "青森市",
    cityKana: "あおもりし",
  },
  {
    id: 3,
    name: "岩手県",
    nameRoman: "iwate",
    nameKana: "いわてけん",
    city: "盛岡市",
    cityKana: "もりおかし",
  },
  {
    id: 4,
    name: "宮城県",
    nameRoman: "miyagi",
    nameKana: "みやぎけん",
    city: "仙台市",
    cityKana: "せんだいし",
  },
  {
    id: 5,
    name: "秋田県",
    nameRoman: "akita",
    nameKana: "あきたけん",
    city: "秋田市",
    cityKana: "あきたし",
  },
  {
    id: 6,
    name: "山形県",
    nameRoman: "yamagata",
    nameKana: "やまがたけん",
    city: "山形市",
    cityKana: "やまがたし",
  },
  {
    id: 7,
    name: "福島県",
    nameRoman: "fukushima",
    nameKana: "ふくしまけん",
    city: "福島市",
    cityKana: "ふくしまし",
  },
  {
    id: 8,
    name: "茨城県",
    nameRoman: "ibaraki",
    nameKana: "いばらきけん",
    city: "水戸市",
    cityKana: "みとし",
  },
  {
    id: 9,
    name: "栃木県",
    nameRoman: "tochigi",
    nameKana: "とちぎけん",
    city: "宇都宮市",
    cityKana: "うつのみやし",
  },
  {
    id: 10,
    name: "群馬県",
    nameRoman: "gunma",
    nameKana: "ぐんまけん",
    city: "前橋市",
    cityKana: "まえばしし",
  },
  {
    id: 11,
    name: "埼玉県",
    nameRoman: "saitama",
    nameKana: "さいたまけん",
    city: "さいたま市",
    cityKana: "さいたまし",
  },
  {
    id: 12,
    name: "千葉県",
    nameRoman: "chiba",
    nameKana: "ちばけん",
    city: "千葉市",
    cityKana: "ちばし",
  },
  {
    id: 13,
    name: "東京都",
    nameRoman: "tokyo",
    nameKana: "とうきょうと",
    city: "東京23区",
    cityKana: "とうきょう23く",
  },
  {
    id: 14,
    name: "神奈川県",
    nameRoman: "kanagawa",
    nameKana: "かながわけん",
    city: "横浜市",
    cityKana: "よこはまし",
  },
  {
    id: 15,
    name: "新潟県",
    nameRoman: "nigata",
    nameKana: "にいがたけん",
    city: "新潟市",
    cityKana: "にいがたし",
  },
  {
    id: 16,
    name: "富山県",
    nameRoman: "toyama",
    nameKana: "とやまけん",
    city: "富山市",
    cityKana: "とやまし",
  },
  {
    id: 17,
    name: "石川県",
    nameRoman: "ishikawa",
    nameKana: "いしかわけん",
    city: "金沢市",
    cityKana: "かなざわし",
  },
  {
    id: 18,
    name: "福井県",
    nameRoman: "fukui",
    nameKana: "ふくいけん",
    city: "福井市",
    cityKana: "ふくいし",
  },
  {
    id: 19,
    name: "山梨県",
    nameRoman: "yamanashi",
    nameKana: "やまなしけん",
    city: "甲府市",
    cityKana: "こうふし",
  },
  {
    id: 20,
    name: "長野県",
    nameRoman: "nagano",
    nameKana: "ながのけん",
    city: "長野市",
    cityKana: "ながのし",
  },
  {
    id: 21,
    name: "岐阜県",
    nameRoman: "gifu",
    nameKana: "ぎふけん",
    city: "岐阜市",
    cityKana: "ぎふし",
  },
  {
    id: 22,
    name: "静岡県",
    nameRoman: "shizuoka",
    nameKana: "しずおかけん",
    city: "静岡市",
    cityKana: "しずおかし",
  },
  {
    id: 23,
    name: "愛知県",
    nameRoman: "aichi",
    nameKana: "あいちけん",
    city: "名古屋市",
    cityKana: "なごやし",
  },
  {
    id: 24,
    name: "三重県",
    nameRoman: "mie",
    nameKana: "みえけん",
    city: "津市",
    cityKana: "つし",
  },
  {
    id: 25,
    name: "滋賀県",
    nameRoman: "shiga",
    nameKana: "しがけん",
    city: "大津市",
    cityKana: "おおつし",
  },
  {
    id: 26,
    name: "京都府",
    nameRoman: "kyoto",
    nameKana: "きょうとふ",
    city: "京都市",
    cityKana: "きょうとし",
  },
  {
    id: 27,
    name: "大阪府",
    nameRoman: "osaka",
    nameKana: "おおさかふ",
    city: "大阪市",
    cityKana: "おおさかし",
  },
  {
    id: 28,
    name: "兵庫県",
    nameRoman: "hyogo",
    nameKana: "ひょうごけん",
    city: "神戸市",
    cityKana: "こうべし",
  },
  {
    id: 29,
    name: "奈良県",
    nameRoman: "nara",
    nameKana: "ならけん",
    city: "奈良市",
    cityKana: "ならし",
  },
  {
    id: 30,
    name: "和歌山県",
    nameRoman: "wakayama",
    nameKana: "わかやまけん",
    city: "和歌山市",
    cityKana: "わかやまし",
  },
  {
    id: 31,
    name: "鳥取県",
    nameRoman: "tottori",
    nameKana: "とっとりけん",
    city: "鳥取市",
    cityKana: "とっとりし",
  },
  {
    id: 32,
    name: "島根県",
    nameRoman: "shimane",
    nameKana: "しまねけん",
    city: "松江市",
    cityKana: "まつえし",
  },
  {
    id: 33,
    name: "岡山県",
    nameRoman: "okayama",
    nameKana: "おかやまけん",
    city: "岡山市",
    cityKana: "おかやまし",
  },
  {
    id: 34,
    name: "広島県",
    nameRoman: "hiroshima",
    nameKana: "ひろしまけん",
    city: "広島市",
    cityKana: "ひろしまし",
  },
  {
    id: 35,
    name: "山口県",
    nameRoman: "yamaguchi",
    nameKana: "やまぐちけん",
    city: "山口市",
    cityKana: "やまぐちし",
  },
  {
    id: 36,
    name: "徳島県",
    nameRoman: "tokushima",
    nameKana: "とくしまけん",
    city: "徳島市",
    cityKana: "とくしまし",
  },
  {
    id: 37,
    name: "香川県",
    nameRoman: "kagawa",
    nameKana: "かがわけん",
    city: "高松市",
    cityKana: "たかまつし",
  },
  {
    id: 38,
    name: "愛媛県",
    nameRoman: "ehime",
    nameKana: "えひめけん",
    city: "松山市",
    cityKana: "まつやまし",
  },
  {
    id: 39,
    name: "高知県",
    nameRoman: "kochi",
    nameKana: "こうちけん",
    city: "高知市",
    cityKana: "こうちし",
  },
  {
    id: 40,
    name: "福岡県",
    nameRoman: "fukuoka",
    nameKana: "ふくおかけん",
    city: "福岡市",
    cityKana: "ふくおかし",
  },
  {
    id: 41,
    name: "佐賀県",
    nameRoman: "saga",
    nameKana: "さがけん",
    city: "佐賀市",
    cityKana: "さがし",
  },
  {
    id: 42,
    name: "長崎県",
    nameRoman: "nagasaki",
    nameKana: "ながさきけん",
    city: "長崎市",
    cityKana: "ながさきし",
  },
  {
    id: 43,
    name: "熊本県",
    nameRoman: "kumamoto",
    nameKana: "くまもとけん",
    city: "熊本市",
    cityKana: "くまもとし",
  },
  {
    id: 44,
    name: "大分県",
    nameRoman: "oita",
    nameKana: "おおいたけん",
    city: "大分市",
    cityKana: "おおいたし",
  },
  {
    id: 45,
    name: "宮崎県",
    nameRoman: "miyazaki",
    nameKana: "みやざきけん",
    city: "宮崎市",
    cityKana: "みやざきし",
  },
  {
    id: 46,
    name: "鹿児島県",
    nameRoman: "kagoshima",
    nameKana: "かごしまけん",
    city: "鹿児島市",
    cityKana: "かごしまし",
  },
  {
    id: 47,
    name: "沖縄県",
    nameRoman: "okinawa",
    nameKana: "おきなわけん",
    city: "那覇市",
    cityKana: "なはし",
  },
];
